version: '3.8'

services:
  # MySQL Database (For production use. Create a .env file for variables)
  mysql:
    image: mysql:8.0
    container_name: inventory-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - inventory-network

  # H2 Database (For development use only)
  h2:
    image: oscarfonts/h2
    container_name: inventory-h2
    restart: unless-stopped
    environment:
      H2_OPTIONS: -ifNotExists
    ports:
      - "8082:81" # Web console
      - "9092:9092" # TCP port
    volumes:
      - h2_data:/h2-data
    networks:
      - inventory-network

volumes:
  mysql_data:
  h2_data:

networks:
  inventory-network:
    driver: bridge